name: Build Endpoints

on:
  # push:
  #   branches:
  #     - main

  schedule:
    - cron: "5 */6 * * *" # national day
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  OUTPUT_FILE_DIR: "dist/"
  APP_ENV: ${{ vars.APP_ENV || 'production' }}
  CRAWLEE_HEADLESS: 1
  CRAWLEE_STORAGE_DIR: ".crawlee"
  TZ: "America/New_York"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 👷  Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: 🏗️ Setup Node.js ${{ vars.NODE_VERSION }} environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        id: setup-node
        with:
          node-version: ${{ vars.NODE_VERSION }}
          check-latest: true

      - name: 🏗️ Setup Nub
        uses: nubjs/setup-nub@47e5e7393d50f4e9544ddaf756aa277972afba2d # v0.4.0

      - name: ⚡  Cache node_modules
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-

      - name: ⬆️ Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: 🛠️ Run script to generate national day data
        run: nub run national-day

      - name: 🛠️ Run script to generate trending repo data
        run: nub run github-trending-repos

      - name: 🛠️ Run script to generate documentation
        run: nub run typedoc-html

      - name: 📦 Create and upload build artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: api-endpoints
          path: ${{ env.OUTPUT_FILE_DIR }}
          retention-days: 1

  call-deploy-workflow:
    needs: [build]
    uses: mikesprague/reusable-workflows/.github/workflows/pages-deploy.yml@main
    secrets:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN}}
    with:
      artifact-name: api-endpoints
      file-name: docs/
