name: Build Endpoints

on:
  push:
    branches:
      - main

  schedule:
    - cron: "5 * * * *"
    - cron: "5 7 * * SUN"
    - cron: "5 4 1,8,15,22,29 * *"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  OUTPUT_FILE_DIR: "dist/"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 👷 Checkout Repo
        uses: actions/checkout@v6

      - name: 🏗️ Setup Bun environment
        id: setup-bun
        uses: oven-sh/setup-bun@v2

      - name: ⚡ Cache node_modules
        uses: actions/cache@v5
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ steps.setup-bun.outputs.bun-version }}-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ steps.setup-bun.outputs.bun-version }}-

      - name: ⬆️ Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: bun install

      - name: ⚡ Cache national day data
        uses: actions/cache@v5
        id: national-day-cache
        with:
          path: ${{ env.OUTPUT_FILE_DIR }}national-day/
          key: ${{ runner.os }}-national-day-${{ steps.setup-bun.outputs.bun-version }}-${{ hashFiles('**/national-day/index.json') }}
          restore-keys: |
            ${{ runner.os }}-national-day-${{ steps.setup-bun.outputs.bun-version }}-

      - name: 🛠️ Run script to generate national day data
        if: github.event.schedule == '5 * * * *' || github.event_name == 'workflow_dispatch'
        run: bun run national-day

      - name: ⚡ Cache national week data
        uses: actions/cache@v5
        id: national-week-cache
        with:
          path: ${{ env.OUTPUT_FILE_DIR }}national-week/
          key: ${{ runner.os }}-national-week-${{ steps.setup-bun.outputs.bun-version }}-${{ hashFiles('**/national-week/index.json') }}
          restore-keys: |
            ${{ runner.os }}-national-week-${{ steps.setup-bun.outputs.bun-version }}-

      - name: 🛠️ Run script to generate national week data
        if: github.event.schedule == '5 7 * * SUN' || github.event_name == 'workflow_dispatch'
        run: bun run national-week

      - name: ⚡ Cache national month data
        uses: actions/cache@v5
        id: national-month-cache
        with:
          path: ${{ env.OUTPUT_FILE_DIR }}national-month/
          key: ${{ runner.os }}-national-month-${{ steps.setup-bun.outputs.bun-version }}-${{ hashFiles('**/national-month/index.json') }}
          restore-keys: |
            ${{ runner.os }}-national-month-${{ steps.setup-bun.outputs.bun-version }}-

      - name: 🛠️ Run script to generate national month data
        if: github.event.schedule == '5 4 1,8,15,22,29 * *' || github.event_name == 'workflow_dispatch'
        run: bun run national-month

      - name: 🛠️ Run script to generate trending repo data
        run: bun run github-trending-repos

      - name: 🛠️ Run script to generate documentation
        if: always()
        run: bun run typedoc-html

      - name: 📦 Create and upload build artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: api-endpoints
          path: ${{ env.OUTPUT_FILE_DIR }}
          retention-days: 1

  call-deploy-workflow:
    needs: [build]
    if: always()
    uses: mikesprague/reusable-workflows/.github/workflows/pages-deploy.yml@main
    secrets:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN}}
    with:
      artifact-name: api-endpoints
      file-name: docs/
